### ISSUE TITLE
What is them main difference with `django-pydantic-field` repo?

### ISSUE THREAD

**Issue by sshishov** [bguggs/django-pydantic-jsonfield#2]
Hi dear maintainer,

Could you please elaborate what is the main difference (will be or now) from similar package: https://github.com/surenkov/django-pydantic-field

Currently we are deciding which route we should go with validated JSON fields using pydantic and trying to get the proper package... What is the vision for this, could we expect to have good widget instead of PrettyJSON, like this for instance: https://github.com/surenkov/django-pydantic-field

Best regards,
    Sergei

**Comment by bguggs** [comment]
My understanding is that these are similar, and the primary differences are around complexity, features, and implementation choices. If you're using this for a major project, I'd recommend using the other library: https://github.com/surenkov/django-pydantic-field. I believe it's better supported than this project at this point. That may change in the future.
